services:
  - type: web
    name: one-dot-server
    runtime: node
    rootDir: server
    buildCommand: npm install --build-from-source=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
